name: Deploy Personal Todo App to GitHub Pages

on:
  push:
    branches:
      - main  # Change to your default branch if it's not 'main'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable GitHub Pages (if not enabled)
        uses: actions/configure-pages@v5
        with:
          enablement: true

      - name: Prepare site files
        run: |
          mkdir public
          # Rename personal_todo_app.html to index.html for GitHub Pages
          cp personal_todo_app.html public/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public



      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
          with:
            token: ${{ secrets.GH_PAT }}
